# Generated by Django 3.0.3 on 2020-04-18 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='location',
            field=models.CharField(default='Unspecified', max_length=30),
        ),
    ]
